### ISSUE TITLE
Need Information about how to get more information in metric labels and custom metric collection

### ISSUE THREAD

**Issue by jmg011** [PureStorage-OpenConnect/pure-fb-openmetrics-exporter#2]
purefb_alerts_open metric has below labels:

- component_name
- component_type
- severity 

1) Is there a way to capture more detailed Alert information - probably short summary and description as part of the labels?
2) If I want to collect more information about the metrics which are currently not part of the exporter, is there a way for me to build some object template for the data collection that exporter will export?

**Comment by genegr** [comment]
The way alerts metrics (and all the metrics reported by the exporter in general) are built is through direct invoking Pure FB REST API and in this case the only information that is made available by the API is the type of the alert and the counter of the related events. There is anyhow possibility to go deeper when a sllightly different approach is used, that is when also the FB logs are collected and sent for instance to ElasticSearch together with the exporter metrics. In that case it is possible to cross correlate the events and analyze them. This is a nice and not negligible side effect enabled by the exporter.

**Comment by jmg011** [comment]
@genegr - How do I query the FB logs? 

From the Alerts point of view, adding a TYPE description to the metric label makes more sense, because that I can send as a part of the alert. Of course, logs and ES will be more useful for further details. Is it possible to add TYPE description to the purefb_alerts_open metric?

**Comment by genegr** [comment]
Well, the problem with metrics like these that are related to logged messages is that there is not a canonical way to group/classify the messages so that it could be possible to add something like the TYPE description you are proposing. All what we have is the object we get as the response from the API call, which has among the others a summary description, but that is neither short enough nor "standardized" to be assumed as a categorization for the object itself. I frankly do not have a solution to that at the moment.
