### ISSUE TITLE
Is it possible to have a breakdown of the file system?

### ISSUE THREAD

**Issue by IK067408** [PureStorage-OpenConnect/pure-fb-openmetrics-exporter#55]
I pulled the /metrics and I don't see a more granular look at the file system.  Below is what I would like to see
purefb-01> purefs list
Name                 Size  Virtual  Hard Limit  Source  Created                  Protocols  Writable  Promotion Status
EA1__dss135          10T   3.60T    True        -       2024-01-11 14:55:53 CST  nfsv3      True      promoted
                                                                                 nfsv4.1
EA1__dss136          10T   0.00     True        -       2024-02-07 11:36:21 CST  nfsv3      True      promoted
                                                                                 nfsv4.1
EA1__dss137          10T   0.00     True        -       2024-02-07 11:37:10 CST  nfsv3      True      promoted
                                                                                 nfsv4.1
EA1__dss138          10T   0.00     True        -       2024-02-07 11:37:55 CST  nfsv3      True      promoted
                                                                                 nfsv4.1
EA1__dss139          10T   0.00     True        -       2024-02-07 11:40:39 CST  nfsv3      True      promoted
                                                                                 nfsv4.1
EA1__dss140          10T   0.00     True        -       2024-02-07 11:41:20 CST  nfsv3      True      promoted
                                                                                 nfsv4.1
EA1__dss141          10T   0.00     True        -       2024-02-07 11:42:04 CST  nfsv3      True      promoted
                                                                                 nfsv4.1
EA1__dss142          10T   0.00     True        -       2024-02-07 11:42:44 CST  nfsv3      True      promoted
                                                                                 nfsv4.1
EA1__dss143          10T   0.00     True        -       2024-02-07 11:43:24 CST  nfsv3      True      promoted
                                                                                 nfsv4.1
EA1__dss144          10T   0.00     True        -       2024-02-07 11:44:10 CST  nfsv3      True      promoted

I have the attached, but I would like to have a more granular look especially Name,size virtual and maybe protocal
![image](https://github.com/PureStorage-OpenConnect/pure-fb-openmetrics-exporter/assets/46282923/967e2a50-2b1a-440f-a86e-feaa995b0879)

**Comment by james-laing** [comment]
Hi @IK067408 thanks for reaching out with feedback.

The purpose of the dashboard is more of a holistic view of your entire fleet with the ability to drill down into useful detail.

While your request is possible, it has some challenges when it scales to more than 5-6 filesystems. The great thing about Grafana though is, it has a large user base with tons customisable options and there is a ton of resources to access to learn and get help.

Here is a simple example of your request if you would like to experiment with it.

<img width="1809" alt="Screenshot 2024-03-07 at 11 54 49" src="https://github.com/PureStorage-OpenConnect/pure-fb-openmetrics-exporter/assets/102221031/1e5d34c7-a145-4eef-a462-170c7ad45885">

Grafana actually stops drawing the pie due to the number of results returned for a single array.

However - in the latest version 1.0.4 of the [//FB dashboard](https://grafana.com/grafana/dashboards/18516-pure-storage-flashblade-overview/) we added some capacity management monitoring for capacity vs physical used.
If you edit the panel, you will find a cool easter egg containing two optional queries you can enable which provide a breakdown of filesystem vs S3 utilisation (unique & snapshots).
<img width="1818" alt="Screenshot 2024-03-07 at 12 07 35" src="https://github.com/PureStorage-OpenConnect/pure-fb-openmetrics-exporter/assets/102221031/c31f5e1a-c8bd-46f7-ba1a-f24f68b0865e">
